### ISSUE TITLE
queue configuration

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#171]
``` 
domain:
  queue:
    default:
      directory: "${CASUAL_DOMAIN_HOME}/queue/groups"
 ``` 
casual does not respect `domain.queue.default.directory`

Either fix it, or remove it from documentation. The latter is somewhat "breaking"
