### ISSUE TITLE
casual domain --configuration-get does not correctly show restart property for executables

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#240]
Config:
```
domain:
  default:
    executable:
      restart: true
  executables:
  - alias: some-executable
    path: /path/to/exe
```
casual domain --list-executables:
```
alias                     CI  I  restart  #r  path                                                             
------------------------  --  -  -------  --  -----------------------------------------------------------------
some-executable            1  1     true   0  "/path/to/exe"     
```
casual domain --configuration-get:
```
- path: "/path/to/exe"
  alias: "some-executable"
  arguments: []
  instances: 1
  restart: false
```
