### ISSUE TITLE
configuration - default values override user specified values when using multiple config files

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#244]
Consider the following config files:

global.yaml
```
domain:
  name: A

  global:
    service:
      execution:
        timeout:
          duration: 45
          contract: "terminate"
```

other.yaml
```
domain:
  servers:
  - path: ${CASUAL_HOME}/example/bin/casual-example-server
```

If casual is started with `casual domain -b global.yaml other.yaml` the default values for services will be a timeout duration of 45s but the default contract will be "linger", even though other.yaml doesnt explicitly override this value.

Observed for the "contract" option in the global service config, might be present elsewhere.
