### ISSUE TITLE
Service describe with format - word 'attributes' misspelled?

### ISSUE THREAD

**Issue by Alex-Erik** [casualcore/casual#264]
Is the word 'attributes' misspelled in the service describe command where format is specified? For example: `casual service describe .casual/service/state yaml`

```
model:
  service: ".casual/service/state"
  arguments:
    input:
      []
    output:
      - role: "result"
        category: 2
        attribues: ...
```
