### ISSUE TITLE
editing the configuration of a service with --configuration-edit creates an empty route to that service

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#370]
Reproduce:

Start a domain with the following config:
```yaml
domain:
  name: blah

  servers:
   - path: ${CASUAL_HOME}/example/bin/casual-example-server
     instances: 1

  services:
    - name: casual/example/echo
      execution:
        timeout:
          duration: 1min
          contract: kill
```

Use `casual domain --configuration-edit` to edit the service (for instance, set the timeout to 2min).

Call `casual internal --state-dump` on the service manager, there will be an empty route:
```
routes: [[ casual/example/echo, []]]
```
