### ISSUE TITLE
Service manager ignores "global" when performing runtime configuration updates

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#377]
```yaml
domain:
  name: ford_prefect
  global:
    # changing any of the below through, for instance, --configuration-edit or --configuration-post will have no effect
    service:
      execution:
        timeout:
          duration: "2min"
          contract: "kill"
```
