### ISSUE TITLE
Enabling a server does not add it as an instance in routes pointing to its services

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#431]
Reproduce:

Boot the following domain:
```yaml
domain:
  name: test

  groups:
    - name: my-group
      enabled: false

  servers:
    - path: ${CASUAL_HOME}/example/bin/casual-example-server
      instances: 1
      memberships:
        - my-group

  services:
    -  name: casual/example/domain/name
       routes: [ my-route]
```

Try to call the route:
```
$ echo "" | casual buffer --compose | casual call --service my-route | casual buffer --extract
[xatmi:TPENOENT] TPENOENT
```

Enable the group:
```
$ casual configuration --enable-groups my-group
```

Call the route again:
```
$ echo "" | casual buffer --compose | casual call --service my-route | casual buffer --extract
[xatmi:TPENOENT] TPENOENT
```
Here one would expect the call to succeed since there is now an instance of the service to which the route points.
