### ISSUE TITLE
Editing queue 'enable' values with configuration --edit has no effect

### ISSUE THREAD

**Issue by AlbsAgren** [casualcore/casual#464]

**Comment by AlbsAgren** [comment]
```yaml
domain:
  queue:
    groups:
      - alias: A
        queues:
          - name: a
            enable:
              # changing below values does nothing at runtime
              enqueue: true
              dequeue: false
```
