### ISSUE TITLE
feature - enable/disable grouping/partitioning of "stuff", as part of the configuration

### ISSUE THREAD

**Issue by albinsjolund** [casualcore/casual#6]
### The proposal is as follows:

- Use te same semantics as with groups for servers/extecutables
- Add "enable/disable" property on group
- gateway - (group of?) connections have 0..* memberships (hence bootorder, enable/disable are respected).
- queue - (group of?) queues/forward have 0..* memberships (hence bootorder, enable/disable are respected).

One semantic problem is the granularity of the "grouping", what is a good "size"?

### Consequences

- groups in gateway-(inbound/outbound) has to be called something else
- groups in queue and queue-forward has to be called something else

Let's say we call this container instead (correspond to one process). We hope that we can reason and configure grouping orthogonal to container. The "need" to keep some stuff in one process could be orthogonal to the "need" to group "stuff".

**Comment by AlbsAgren** [comment]
## Some notes

### Group cli rough draft (casual domain ...)
--list-groups
--enable-group \<name\>      # enable a group
--disable-group \<name\>     # disable a group
--describe-group \<name\>   # list the members, dependencies etc of a group
--list-memberships \<alias\>  # list all the groups to which "alias" belongs

### Config
```yaml
domain:
  groups:
    - name: "common-group"
      note: "group that logically groups 'common' stuff"
      enabled: true | false
    - name: "customer-group"
      note: "group that logically groups 'customer' stuff"
      resources:
        - "customer-db"
      dependencies:
        - "common-group"

  servers:
    - path: "/some/path/customer-server-1"
      memberships:
        - "customer-group"

  executables:
    - path: "/some/path/mq-server"
      memberships:
        - "common-group"
      arguments:
        - ...

  queue:
    forward:
      groups:
        - alias: my-forward
          memberships:
            - "common-group"
          services:
            - ...
  gateway:
    outbound:
      groups:
        - alias: my-outbound
          memberships:
            - "common-group"
          connections:
            - address: 127...
    inbound:
      reverse:
        - alias: my-reverse-inbound
          memberships:
            - "common-group"
          connections:
            - address: 127...
```

### Notes

- Disabled has precedence, i.e. if an alias is a member of one disabled group, it itself is disabled, even if it is also a member of other enabled groups
- Similarly, if a dependency of a group is disabled, so is the group itself
- Disabled aliases should still be visible, for example by listing them with 0 instances, or some other flag in the cli output
